# Generated by Django 6.0.5 on 2026-06-22 04:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('passenger_name', models.CharField(max_length=120)),
                ('passenger_phone', models.CharField(max_length=30)),
                ('start_location', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=160)),
                ('trip_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency', 'Emergency')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trip_status'], name='trips_trip_trip_st_ea7a7b_idx'), models.Index(fields=['started_at'], name='trips_trip_started_59d56d_idx'), models.Index(fields=['created_at'], name='trips_trip_created_b7c7fb_idx'), models.Index(fields=['driver', 'trip_status'], name='trips_trip_driver__3871af_idx'), models.Index(fields=['vehicle', 'trip_status'], name='trips_trip_vehicle_6747a4_idx')],
            },
        ),
    ]
