# Generated by Django 6.0.5 on 2026-06-22 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['alert_type'], name='emergency_e_alert_t_7cdce7_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status'], name='emergency_e_status_913972_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['created_at'], name='emergency_e_created_c916fc_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['trip', 'status'], name='emergency_e_trip_id_78af21_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['user', 'created_at'], name='emergency_e_user_id_aca4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['created_at'], name='emergency_e_created_40efcf_idx'),
        ),
    ]
