# Generated by Django 6.0.5 on 2026-08-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyalert",
            name="details_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="SOSAuthorityContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("authority_name", models.CharField(max_length=160)),
                ("official_email", models.EmailField(max_length=254)),
                ("sms_phone_number", models.CharField(max_length=30)),
                ("physical_jurisdiction", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["authority_name"],
            },
        ),
        migrations.CreateModel(
            name="SOSAlertDeliveryLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_type", models.CharField(choices=[("authority", "Authority"), ("admin", "Admin")], max_length=20)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=20)),
                ("destination", models.CharField(max_length=160)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped")], db_index=True, default="pending", max_length=20)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("response_message", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("admin_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sos_delivery_logs", to=settings.AUTH_USER_MODEL)),
                ("alert", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delivery_logs", to="emergency.emergencyalert")),
                ("authority_contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="delivery_logs", to="emergency.sosauthoritycontact")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SOSAuthorityAccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("list", "List"), ("create", "Create"), ("update", "Update"), ("delete", "Delete")], max_length=20)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("admin_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sos_authority_access_logs", to=settings.AUTH_USER_MODEL)),
                ("authority_contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="access_logs", to="emergency.sosauthoritycontact")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sosauthoritycontact",
            index=models.Index(fields=["is_active", "authority_name"], name="emergency_s_is_activ_1a8c94_idx"),
        ),
        migrations.AddIndex(
            model_name="sosauthoritycontact",
            index=models.Index(fields=["physical_jurisdiction"], name="emergency_s_physica_8d98a1_idx"),
        ),
        migrations.AddIndex(
            model_name="sosalertdeliverylog",
            index=models.Index(fields=["alert", "status"], name="emergency_s_alert_i_5f4c7b_idx"),
        ),
        migrations.AddIndex(
            model_name="sosalertdeliverylog",
            index=models.Index(fields=["recipient_type", "channel"], name="emergency_s_recipie_2f3c1b_idx"),
        ),
        migrations.AddIndex(
            model_name="sosauthorityaccesslog",
            index=models.Index(fields=["admin_user", "created_at"], name="emergency_s_admin_u_b8e34a_idx"),
        ),
        migrations.AddIndex(
            model_name="sosauthorityaccesslog",
            index=models.Index(fields=["action", "created_at"], name="emergency_s_action__b3f905_idx"),
        ),
    ]

