# Generated by Django 6.0.5 on 2026-08-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_sos_authority_contacts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sosalertdeliverylog',
            new_name='emergency_s_alert_i_6465f1_idx',
            old_name='emergency_s_alert_i_5f4c7b_idx',
        ),
        migrations.RenameIndex(
            model_name='sosalertdeliverylog',
            new_name='emergency_s_recipie_54623f_idx',
            old_name='emergency_s_recipie_2f3c1b_idx',
        ),
        migrations.RenameIndex(
            model_name='sosauthorityaccesslog',
            new_name='emergency_s_admin_u_ff8f9d_idx',
            old_name='emergency_s_admin_u_b8e34a_idx',
        ),
        migrations.RenameIndex(
            model_name='sosauthorityaccesslog',
            new_name='emergency_s_action_027c59_idx',
            old_name='emergency_s_action__b3f905_idx',
        ),
        migrations.RenameIndex(
            model_name='sosauthoritycontact',
            new_name='emergency_s_is_acti_803136_idx',
            old_name='emergency_s_is_activ_1a8c94_idx',
        ),
        migrations.RenameIndex(
            model_name='sosauthoritycontact',
            new_name='emergency_s_physica_6c379b_idx',
            old_name='emergency_s_physica_8d98a1_idx',
        ),
    ]
