# Generated by Django 6.0.5 on 2026-08-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_email_notification_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailnotificationlog',
            new_name='coyour-resend-api-key-here',
            old_name='coyour-resend-api-key-here',
        ),
        migrations.RenameIndex(
            model_name='emailnotificationlog',
            new_name='coyour-resend-api-key-here',
            old_name='coyour-resend-api-key-here',
        ),
    ]
