"""
Django settings for saferide project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Compute DEBUG BEFORE the SECRET_KEY gate so dev vs production policy
# can be decided without ever baking a static fallback key into source.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# NEVER bake a default fallback secret into source — require DJANGO_SECRET_KEY env var.
#   * If the env var is set: always use it, regardless of DEBUG.
#   * Else when DEBUG=True (dev/staging): generate a throwaway per-process key so
#     local `manage.py` and any dev container still boots out of the box.
#   * Else when DEBUG=False (production): refuse to start — a long-lived key MUST
#     be configured explicitly for production (sessions/signing tokens depend on it).
_SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not _SECRET_KEY:
    if DEBUG:
        try:
            from django.core.management.utils import get_random_secret_key
            _SECRET_KEY = get_random_secret_key()
        except Exception:  # pragma: no cover - Django import guard
            import secrets
            _SECRET_KEY = "django-insecure-" + secrets.token_urlsafe(38)
    else:
        raise RuntimeError(
            "DJANGO_SECRET_KEY environment variable is required for production. "
            "Copy .env.example -> .env and set DJANGO_SECRET_KEY to a long random string."
        )
SECRET_KEY = _SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
# (DEBUG was computed above; alias kept for readability.)

ALLOWED_HOSTS = [".localhost", "127.0.0.1", "[::1]", "testserver", ".railway.app", ".rideguarde.com", "rideguarde.com"]

CSRF_TRUSTED_ORIGINS = ["https://*.up.railway.app", "https://rideguardeng-production.up.railway.app", "https://rideguarde.com", "https://*.rideguarde.com"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "core",
    "accounts",
    "drivers",
    "dashboard",
    "apps.vehicles",
    "apps.trips",
    "apps.emergency",
    "apps.reports",
    "apps.tracking",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saferide.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saferide.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_DRIVER_DOCUMENTS_ROOT = BASE_DIR / "private_media" / "driver_documents"
PRIVATE_DRIVER_DOCUMENTS_BACKUP_ROOT = BASE_DIR / "private_media_backup" / "driver_documents"
DRIVER_DOCUMENT_MAX_UPLOAD_BYTES = int(os.environ.get("DRIVER_DOCUMENT_MAX_UPLOAD_BYTES", str(8 * 1024 * 1024)))
DRIVER_DOCUMENT_MALWARE_SCAN_ENABLED = os.environ.get("DRIVER_DOCUMENT_MALWARE_SCAN_ENABLED", "False") == "True"

AUTH_USER_MODEL = "accounts.User"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "admin:index"
TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]
DRIVER_PII_ENCRYPTION_KEY = os.environ.get("DRIVER_PII_ENCRYPTION_KEY", SECRET_KEY)

# Channels Configuration
ASGI_APPLICATION = 'saferide.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    },
}

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@rideguarde.com")
SOS_SMS_PROVIDER = os.environ.get("SOS_SMS_PROVIDER", "console")
SOS_SMS_HTTP_ENDPOINT = os.environ.get("SOS_SMS_HTTP_ENDPOINT", "")
SOS_SMS_HTTP_AUTH_TOKEN = os.environ.get("SOS_SMS_HTTP_AUTH_TOKEN", "")
SOS_SMS_HTTP_SENDER_ID = os.environ.get("SOS_SMS_HTTP_SENDER_ID", "SafeRide")

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", DEFAULT_FROM_EMAIL)
ADMIN_NOTIFICATION_EMAILS = [email.strip() for email in os.environ.get("ADMIN_NOTIFICATION_EMAILS", "").split(",") if email.strip()]

