# Generated by Django 6.0.5 on 2026-08-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_tripshayour-resend-api-key-here'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='locationupdate',
            new_name='tracking_lo_trip_sh_55e652_idx',
            old_name='apps_tracking_locationtrip_shayour-resend-api-key-here',
        ),
    ]
