# Generated by Django 6.0.5 on 2026-06-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['report_type'], name='reports_inc_report__8da3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status'], name='reports_inc_status_24c31e_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['created_at'], name='reports_inc_created_5abae7_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['trip', 'status'], name='reports_inc_trip_id_663162_idx'),
        ),
    ]
